cfg_base_dir: H:\Ham_Data
loader: neurochat
loader_kwargs:
  system: Axona
  pos_extension: [.pos]
image_format: png
clean_method: pick_zscore
clean_kwargs:
  pick_property: group_name
  options: [TT0, TT1, TT2, TT3, TT4, TT5, TT6, TT7, TT8, TT9, TT10, TT11, TT12, TT13, TT14, TT15]
z_score_threshold: 1.1
fmin: 0.5
fmax: 120
filter_kwargs:
  copy: True
theta_min: 6
theta_max: 12
delta_min: 1.0
delta_max: 4
low_gamma_min: 40
low_gamma_max: 80
high_gamma_min: 80
high_gamma_max: 120
beta_min: 15
beta_max: 30
psd_scale: decibels
notch_freqs: [50, 60, 100]
max_psd_freq: 40